[build]
  # PWA静态文件，无需构建步骤
  command = "echo 'PWA build complete - no build needed'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# PWA文件重定向
[[redirects]]
  from = "/"
  to = "/demo.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/demo.html" 
  status = 200